# Generated by Django 5.2.12 on 2026-04-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_item_options_rename_name_item_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='runtime',
            field=models.CharField(blank=True, null=True),
        ),
    ]
